# Generated by Django 3.2.8 on 2022-09-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(default='Recieved', max_length=15)),
                ('msg', models.TextField(default='')),
                ('time_stamp', models.CharField(blank=True, max_length=250, null=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('display_phone', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
