# Generated by Django 3.2.8 on 2022-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='msg_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
